### ISSUE TITLE
Invoke-Build:  cmd-line parameter to generate intermediate MSBuild file and exit

### ISSUE THREAD

**Issue by virmitio** [coapp/coapp.powershell#10]
There should be a switch parameter that can be passed to Invoke-Build to write the resultant MSBuild file to the console (where it can optionally be redirected to a file).

Possibly `-EmitOnly`?

**Comment by fearthecowboy** [comment]
Feature Added  in 1.23.207.0 -- to update, use: 

``` powershell
# Update CoApp PowerShell Tools
Update-CoAppTools -KillPowerShells -Beta 
```

Added two new switches : 

`-DumpScript` -- outputs the msbuild script to the screen
`-SaveScript` -- saves the script and returns the filename.
