### ISSUE TITLE
Please release VS2015 support

### ISSUE THREAD

**Issue by forderud** [coapp/coapp.powershell#112]
The latest publicly available (beta) version of CoApp PowerShell seem to be 1.23.521.0. This version does not support the "v140" pivot required for VS2015 support. Attempting to author a native VS2015 NuGet package exits with the following error: 'Write-NuGetPackage : Unmatched configuration choice 'v140''

Support for VS2015 was merged in September 2014 (https://github.com/coapp/coapp.powershell/pull/89), so this appears to be a question of releasing what is already implemented.

**Comment by igagis** [comment]
any plans to release this?

**Comment by igagis** [comment]
I emailed to @fearthecowboy about the issue, let's see if he could help

**Comment by jmecosta** [comment]
you can define the pivots while release is not done.

``` javascript
configurations 
{
                      // This node contains custom pivot information.

                      Toolset 
                      {
                                                   key : "PlatformToolset"; // this is CoApp pre-defined key
                                                   choices: { v140, v120, v110, v100 };
                      };
}
```

**Comment by fearthecowboy** [comment]
I've finally been given time between projects, I'm working on this today.

**Comment by forderud** [comment]
Any progress on fixing this issue?

**Comment by NiViktor** [comment]
I am also running into this issue.
Any update on when the VS 2015 support will be available? 
Thanks!

**Comment by 23W** [comment]
When update come out ?

**Comment by forderud** [comment]
Any progress on fixing this issue?

**Comment by rchom** [comment]
@jmecosta Where does the "configurations {  ... } " workaround go?

**Comment by jmecosta** [comment]
Before the nuget section

**Comment by zabulus** [comment]
workaround works bad if I use v140 and v140_xp projects in my solution.
for <v140 .targets files had next condition, which matches both v110 and v110_xp:

```
 ( $(PlatformToolset.ToLower().IndexOf('v110')) &gt; -1
```

If I use workaround new .targets file contains:

```
'$(PlatformToolset.ToLower())' == 'v140'
```

Which unacceptable for my projects. Any thoughts?

**Comment by jmecosta** [comment]
You can always generate only the prop files with noclean option and the adjust the targets to your needs and generate the nugets yourself?

**Comment by zabulus** [comment]
I've workarounded my issue by following:

```
configurations {
    Toolset { 
        key : "PlatformToolset"; 
        choices: { v140 };  
        // Explicitly Not including pivot variants:  "WindowsKernelModeDriver8.0", "WindowsApplicationForDrivers8.0", "WindowsUserModeDriver8.0" 

        // We're normalizing out the concept of the v140 platform -- Overloading the $(PlatformToolset) variable for additional pivots was a dumb idea.
        v140.condition = "( $(PlatformToolset.ToLower().IndexOf('v140')) > -1 Or '$(PlatformToolset.ToLower())' == 'windowskernelmodedriver8.0' Or '$(PlatformToolset.ToLower())' == 'windowsapplicationfordrivers8.0' Or '$(PlatformToolset.ToLower())' == 'windowsusermodedriver8.0' )";
    };
}
```

CoApp seeks for the `condition` subsection and patches it's content right in a `.targets` file.

**Comment by lgxZJ** [comment]
hasn't fixed yet?

**Comment by forderud** [comment]
Closing, since this is unlikely to ever be fixed. My team have opted to instead use nuspec & targets files directly instead of coapp.
