### ISSUE TITLE
The Includes and Defines target/prop dosen't seem to work

### ISSUE THREAD

**Issue by gordonwatts** [coapp/coapp.powershell#23]
Using latest stable release (or the beta) the Defines keyword in the props or targets section doesn't seem to do anything.

```
   props {
        Includes += "c:\users\fork";
        Defines += "_LATER";
    }        
    targets {
        Includes += "c:\users\fork";
        Defines += "_LATER";
    }
```

Neither of these appears in any of the three files generated (the xml or targets file), and a #ifdef _LATER never fires in a compiled project. My include files and my libraries are correctly picked up and installed by nuget when I add the package to my project.

BTW, I went looking for source code to see if I could figure out what I was doing wrong, but was unable to find it for the ClrPlus library on github or CodePlex.

**Comment by fearthecowboy** [comment]
You've hit me on my most busy week _ever_.

I don't have the most recent code pushed up to github; I was reorganizing it so it all ended up in the same project (I had  a terrible ratsnest of code (which made debugging terribly difficult). I think I can commit to pushing it up tomorrow, and it'll all be in one repo (and build-able!) again.

Can you post your whole .autopkg script? perhaps I can spot the problem -- this sort of thing should be working well at this point.

the other option, you can try, is grab the latest-latest-latest-dev build (not beta/stable) from   http://downloads.coapp.org/files/Development.CoApp.Tools.Powershell.msi  and try that.

This has my latest changes in it that fix some of the oddities, and make it better for splitting up large packages.

**Comment by gordonwatts** [comment]
No worries, thanks! The tool has already been very helpful. Here is my full .autopkg file. Annnd. This is obviously my bug, now that I post it here. I missed that I had targets and props inside the files section, not outside (I've posted the original, incorrect one here). So my bad. Sorry if this took time away from what you are doing. I suppose a small feature request might be an error message when this happens. :-)

```
nuget {
    nuspec {
        id = ROOT;
        version = 5.34.09.0009;
        title = ROOT;
        authors = {CERN};
        owners = {G. Watts};
        licenseUrl: "http://root.cern.ch/drupal/content/license";
        projectUrl: "http://root.cern.ch";
        iconUrl: "http://root.cern.ch/drupal/sites/default/files/rootdrawing-logo.png";
        requireLicenseAcceptance: false;
        summary: The complete ROOT data analysis toolkit for C++;
        description: Contains all libraries needed for the full set of ROOT utilities;
        releaseNotes: "Release v5.34.09 of ROOT";
        tags: data;
    };

    files {
        include: { "root\include\*"};
        [x86,dynamic] {
            lib: { "root\lib\*.lib" };
            bin: { "root\bin\*.dll" };
        };
    }
    props {
        Includes += "c:\users\fork";
        Defines += "_LATER";
    }

    targets {
        Includes += "c:\users\fork";
        Defines += "_LATER";
    }
}
```

**Comment by fearthecowboy** [comment]
Yeah, I've been meaning to go thru and add a bunch of warnings and errors for things when they don't make semantic sense (I overhauled the bubbling up of warnings and errors back in june, but it doesn't say much yet :D )

G

**Comment by gordonwatts** [comment]
Great! I know what it is like to have too much on one's plate. Thanks a lot! And you can close this if you wish!
