### ISSUE TITLE
Support option to just create the nuspec files

### ISSUE THREAD

**Issue by guss77** [coapp/coapp.powershell#40]
Currently we use the CoApp cmdlet to generate the nuget spec files, which we later feed Teamcity's NuGet Pack task. As such, every time we want to create/change an autopkg script we need to run `Write-Nuget -NoClean package.autopkg`, wait for the nupkg to be created and then delete it before committing the changes.

It would be helpful if there would be an option to just create the nuspec files without building the package itself.

**Comment by fearthecowboy** [comment]
Good idea. I'll put that in the next build.

**Comment by fearthecowboy** [comment]
I've added a new switch  `-generateonly` which skips the nupack command, and leaves all the files on disk.

It's in the latest development build, which you can get via an elevated powershell prompt :

`PS >update-coapptools -development -killpowershell`

**Comment by guss77** [comment]
Thanks!

I still have a few issues with using CoApp to generate nuget configuraiton files for Teamcity, for which I'll open new reports.

**Comment by fearthecowboy** [comment]
No problem. Open as many bug reports as you can :D ...

I'm gonna be on vacation for a few weeks, so it might be slow getting to them tho ;)

**Comment by guss77** [comment]
No rush, thanks for this very helpful tool :+1:
