### ISSUE TITLE
How can I build the CoApp installer?

### ISSUE THREAD

**Issue by yodantauber** [coapp/coapp.powershell#58]
Having built CoApp.PowerShell.Tools successfully (from the source currently in the master branch of this GitHub project), I'm now trying to build the installer.
I installed WiX 3.8.
If I just open Installer.wixproj with Visual Studio and try to build it, I get the following error:

```
C:\Program Files (x86)\MSBuild\Microsoft\WiX\v3.x\wix2010.targets(508,7): error : The OutputPath property is not set for this project.  Please check to make sure that you have specified a valid Configuration/Platform combination.  Configuration='Release'  Platform='x86'
```

If I add an output path, I get the following error:

```
Product.wxs(36,0): error CNDL0150: Undefined preprocessor variable '$(env.SolutionDir)'.
```

Should I open the installer project as part of some solution?
Should I somehow build from command line and not from within VS?

**Comment by fearthecowboy** [comment]
I haven't built the installer with the vs project in a while (didn't work with VS2013 last I tried).

You should be able to build the MSI from the command line. 
(uh... whoops) 

I just pushed up a change with my publish.cmd script in it. 

G

**Comment by yodantauber** [comment]
It works with publish.cmd, thanks!
