### ISSUE TITLE
Add allias entries for standard build environments

### ISSUE THREAD

**Issue by virmitio** [coapp/coapp.powershell#9]
Add common alternate aliases for build environments.

eg. `VC_V110_WIN32` == `VC_V110_X86`, `VC_V110_AMD64` == `VC_V110_X64`, etc.

**Comment by fearthecowboy** [comment]
Added in 1.23.207.0 -- To Update, use: 

``` powershell
# Update CoApp PowerShell Tools
Update-CoAppTools -KillPowerShells -Beta 
```
